# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0cdc7e148c64df2dce2751eee3edff52f32ed733202cb6614aa46045e6442c11a0bce64a32d2b7e605225efcc7c349f9c1d78f538488b74cfd672350b7fbde7a

test:
  secret_key_base: 950341af1a24596a9007919fd007b0ceb7fcb24295c61560e31e4288cd5cbbfb8dd24cb81059a1fb370d13c834c4a4fa081e3a89956cd63f2998cfe64909acf3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
